---
name: Build and Deploy react app to pages
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy: 
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install
      
    - name: Test
      run: npm run test
      
    - name: Deploy
      run:
        git config --global user.name 'Pablo Bedolla'
        git config --global user.email 'bedol.pab@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}g@github.com/${{ github.repository }}
        npm run deploy